server:
  port: 8081
spring:
  application:
    name: books-client
  output:
    ansi:
      enabled: always
resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: books-client:8081
    prefer-ip-address: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    io.github.resilience4j: DEBUG
