spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/applique_clothes
    username: postgres
    password: 1234
  sql:
    init:
      mode: always
#      data-locations: classpath:data.sql
#      schema-locations: classpath:schema.sql

#  h2:
#    console:
#      path: /h2-console
#      settings:
#        web-allow-others: true
  output:
    ansi:
      enabled: always
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: false
    show-sql: true
  mvc:
    hiddenmethod:
      filter.enabled: true

web-client:
  base-url: https://api-key.fusionbrain.ai
  x-key: ${X_KEY:}
  x-secret: ${X_SECRET:}
