spring:
  datasource:
#    url: jdbc:h2:mem:maindb
#    url: jdbc:postgresql://localhost:5432/postgres
#    username: postgres
#    password: 1234
    url: jdbc:postgresql://localhost:5432/db_docker
    username: postgres
    password: postgres
  sql:
    init:
      mode: always
#      data-locations: classpath:data.sql
#      schema-locations: classpath:schema.sql

#  h2:
#    console:
#      path: /h2-console
#      settings:
#        web-allow-others: true
  output:
    ansi:
      enabled: always
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: false
    show-sql: true
  mvc:
    hiddenmethod:
      filter.enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: when_authorized
      roles: "ADMIN"
  health:
    defaults:
      enabled: true
  jmx:
    enabled: true

#logging:
#  level:
#    ROOT: DEBUG